;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Effects.Passive.HealthRegen",NewTagName="Effect.Passive.HealthRegen")
+GameplayTagRedirects=(OldTagName="Effects.Passive",NewTagName="Effect.Passive")
+GameplayTagRedirects=(OldTagName="Effects",NewTagName="Effect")
+GameplayTagRedirects=(OldTagName="GameplayEffect.Character.Ability1",NewTagName="GameplayEffect.Camera.Ability1")
+GameplayTagRedirects=(OldTagName="GameplayEffect.Character",NewTagName="GameplayEffect.Camera")
+GameplayTagList=(Tag="Cooldown.Ability.First",DevComment="")
+GameplayTagList=(Tag="Cooldown.Ability.Second",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Effect.Duration",DevComment="")
+GameplayTagList=(Tag="Effect.HitReact.Back",DevComment="")
+GameplayTagList=(Tag="Effect.HitReact.Front",DevComment="")
+GameplayTagList=(Tag="Effect.HitReact.Left",DevComment="")
+GameplayTagList=(Tag="Effect.HitReact.Right",DevComment="")
+GameplayTagList=(Tag="Effect.Passive.HealthRegen",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.SpawnProjectile",DevComment="")
+GameplayTagList=(Tag="Event.Combo.End",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Input",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Triggered",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.AOEAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Character.Forth",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Character.Second",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Character.Third",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOEIndicator",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Charge",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Regen",DevComment="")
+GameplayTagList=(Tag="GameplayCue.LightningBolt",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileImpact.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileImpact.Ice",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileSpawn.Gun",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Camera.Ability1",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Camera.Ability2",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Camera.Ability3",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee",DevComment="")

